// Package docs is auto-generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "swagger": "2.0",
    "info": {
        "description": "A production-ready Job Portal backend with role-based access control.",
        "title": "Job Portal API",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "email": "support@jobportal.com"
        },
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "1.0"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/register": {
            "post": {
                "description": "Create a new account with name, email, password and role",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["Auth"],
                "summary": "Register a new user",
                "parameters": [
                    {
                        "description": "Register payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": { "$ref": "#/definitions/RegisterInput" }
                    }
                ],
                "responses": {
                    "201": { "description": "Created", "schema": { "$ref": "#/definitions/APIResponse" } },
                    "400": { "description": "Bad Request", "schema": { "$ref": "#/definitions/APIResponse" } },
                    "409": { "description": "Conflict", "schema": { "$ref": "#/definitions/APIResponse" } }
                }
            }
        },
        "/auth/login": {
            "post": {
                "description": "Authenticate with email and password, returns a JWT token",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["Auth"],
                "summary": "Login",
                "parameters": [
                    {
                        "description": "Login payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": { "$ref": "#/definitions/LoginInput" }
                    }
                ],
                "responses": {
                    "200": { "description": "OK", "schema": { "$ref": "#/definitions/APIResponse" } },
                    "400": { "description": "Bad Request", "schema": { "$ref": "#/definitions/APIResponse" } },
                    "401": { "description": "Unauthorized", "schema": { "$ref": "#/definitions/APIResponse" } }
                }
            }
        },
        "/jobs": {
            "get": {
                "security": [{ "BearerAuth": [] }],
                "description": "Get paginated list of jobs with optional filters",
                "produces": ["application/json"],
                "tags": ["Jobs"],
                "summary": "List all jobs",
                "parameters": [
                    { "type": "integer", "default": 1, "name": "page", "in": "query" },
                    { "type": "integer", "default": 10, "name": "page_size", "in": "query" },
                    { "type": "string", "name": "location", "in": "query" },
                    { "type": "string", "name": "company", "in": "query" }
                ],
                "responses": {
                    "200": { "description": "OK", "schema": { "$ref": "#/definitions/APIResponse" } },
                    "401": { "description": "Unauthorized", "schema": { "$ref": "#/definitions/APIResponse" } }
                }
            },
            "post": {
                "security": [{ "BearerAuth": [] }],
                "description": "Recruiter creates a new job posting",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["Jobs"],
                "summary": "Create a job",
                "parameters": [
                    {
                        "description": "Job payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": { "$ref": "#/definitions/CreateJobInput" }
                    }
                ],
                "responses": {
                    "201": { "description": "Created", "schema": { "$ref": "#/definitions/APIResponse" } },
                    "400": { "description": "Bad Request", "schema": { "$ref": "#/definitions/APIResponse" } },
                    "403": { "description": "Forbidden", "schema": { "$ref": "#/definitions/APIResponse" } }
                }
            }
        },
        "/jobs/{id}": {
            "get": {
                "security": [{ "BearerAuth": [] }],
                "description": "Retrieve a single job by its UUID",
                "produces": ["application/json"],
                "tags": ["Jobs"],
                "summary": "Get a job by ID",
                "parameters": [
                    { "type": "string", "description": "Job UUID", "name": "id", "in": "path", "required": true }
                ],
                "responses": {
                    "200": { "description": "OK", "schema": { "$ref": "#/definitions/APIResponse" } },
                    "404": { "description": "Not Found", "schema": { "$ref": "#/definitions/APIResponse" } }
                }
            },
            "put": {
                "security": [{ "BearerAuth": [] }],
                "description": "Recruiter updates their own job posting",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["Jobs"],
                "summary": "Update a job",
                "parameters": [
                    { "type": "string", "description": "Job UUID", "name": "id", "in": "path", "required": true },
                    { "description": "Update payload", "name": "body", "in": "body", "required": true, "schema": { "$ref": "#/definitions/UpdateJobInput" } }
                ],
                "responses": {
                    "200": { "description": "OK", "schema": { "$ref": "#/definitions/APIResponse" } },
                    "403": { "description": "Forbidden", "schema": { "$ref": "#/definitions/APIResponse" } },
                    "404": { "description": "Not Found", "schema": { "$ref": "#/definitions/APIResponse" } }
                }
            },
            "delete": {
                "security": [{ "BearerAuth": [] }],
                "description": "Recruiter deletes their own job (Admin can delete any)",
                "produces": ["application/json"],
                "tags": ["Jobs"],
                "summary": "Delete a job",
                "parameters": [
                    { "type": "string", "description": "Job UUID", "name": "id", "in": "path", "required": true }
                ],
                "responses": {
                    "200": { "description": "OK", "schema": { "$ref": "#/definitions/APIResponse" } },
                    "403": { "description": "Forbidden", "schema": { "$ref": "#/definitions/APIResponse" } },
                    "404": { "description": "Not Found", "schema": { "$ref": "#/definitions/APIResponse" } }
                }
            }
        },
        "/jobs/{id}/apply": {
            "post": {
                "security": [{ "BearerAuth": [] }],
                "description": "Candidate submits an application for a job",
                "produces": ["application/json"],
                "tags": ["Applications"],
                "summary": "Apply for a job",
                "parameters": [
                    { "type": "string", "description": "Job UUID", "name": "id", "in": "path", "required": true }
                ],
                "responses": {
                    "201": { "description": "Created", "schema": { "$ref": "#/definitions/APIResponse" } },
                    "404": { "description": "Not Found", "schema": { "$ref": "#/definitions/APIResponse" } },
                    "409": { "description": "Conflict", "schema": { "$ref": "#/definitions/APIResponse" } }
                }
            }
        },
        "/applications": {
            "get": {
                "security": [{ "BearerAuth": [] }],
                "description": "Candidate views their own job applications",
                "produces": ["application/json"],
                "tags": ["Applications"],
                "summary": "My applications",
                "parameters": [
                    { "type": "integer", "default": 1, "name": "page", "in": "query" },
                    { "type": "integer", "default": 10, "name": "page_size", "in": "query" }
                ],
                "responses": {
                    "200": { "description": "OK", "schema": { "$ref": "#/definitions/APIResponse" } },
                    "403": { "description": "Forbidden", "schema": { "$ref": "#/definitions/APIResponse" } }
                }
            }
        },
        "/applications/job/{id}": {
            "get": {
                "security": [{ "BearerAuth": [] }],
                "description": "Recruiter views all applicants for one of their jobs",
                "produces": ["application/json"],
                "tags": ["Applications"],
                "summary": "Applicants for a job",
                "parameters": [
                    { "type": "string", "description": "Job UUID", "name": "id", "in": "path", "required": true },
                    { "type": "integer", "default": 1, "name": "page", "in": "query" },
                    { "type": "integer", "default": 10, "name": "page_size", "in": "query" }
                ],
                "responses": {
                    "200": { "description": "OK", "schema": { "$ref": "#/definitions/APIResponse" } },
                    "403": { "description": "Forbidden", "schema": { "$ref": "#/definitions/APIResponse" } },
                    "404": { "description": "Not Found", "schema": { "$ref": "#/definitions/APIResponse" } }
                }
            }
        },
        "/applications/{id}/status": {
            "patch": {
                "security": [{ "BearerAuth": [] }],
                "description": "Recruiter updates the status of an application",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["Applications"],
                "summary": "Update application status",
                "parameters": [
                    { "type": "string", "description": "Application UUID", "name": "id", "in": "path", "required": true },
                    { "description": "Status payload", "name": "body", "in": "body", "required": true, "schema": { "$ref": "#/definitions/UpdateStatusInput" } }
                ],
                "responses": {
                    "200": { "description": "OK", "schema": { "$ref": "#/definitions/APIResponse" } },
                    "403": { "description": "Forbidden", "schema": { "$ref": "#/definitions/APIResponse" } },
                    "404": { "description": "Not Found", "schema": { "$ref": "#/definitions/APIResponse" } }
                }
            }
        },
        "/admin/users": {
            "get": {
                "security": [{ "BearerAuth": [] }],
                "description": "Admin retrieves all registered users",
                "produces": ["application/json"],
                "tags": ["Admin"],
                "summary": "[Admin] List all users",
                "parameters": [
                    { "type": "integer", "default": 1, "name": "page", "in": "query" },
                    { "type": "integer", "default": 10, "name": "page_size", "in": "query" }
                ],
                "responses": {
                    "200": { "description": "OK", "schema": { "$ref": "#/definitions/APIResponse" } },
                    "403": { "description": "Forbidden", "schema": { "$ref": "#/definitions/APIResponse" } }
                }
            }
        },
        "/admin/users/{id}": {
            "delete": {
                "security": [{ "BearerAuth": [] }],
                "description": "Admin soft-deletes a user by UUID",
                "produces": ["application/json"],
                "tags": ["Admin"],
                "summary": "[Admin] Delete a user",
                "parameters": [
                    { "type": "string", "description": "User UUID", "name": "id", "in": "path", "required": true }
                ],
                "responses": {
                    "200": { "description": "OK", "schema": { "$ref": "#/definitions/APIResponse" } },
                    "404": { "description": "Not Found", "schema": { "$ref": "#/definitions/APIResponse" } }
                }
            }
        },
        "/admin/jobs": {
            "get": {
                "security": [{ "BearerAuth": [] }],
                "description": "Admin retrieves all job postings",
                "produces": ["application/json"],
                "tags": ["Admin"],
                "summary": "[Admin] List all jobs",
                "parameters": [
                    { "type": "integer", "default": 1, "name": "page", "in": "query" },
                    { "type": "integer", "default": 10, "name": "page_size", "in": "query" },
                    { "type": "string", "name": "location", "in": "query" },
                    { "type": "string", "name": "company", "in": "query" }
                ],
                "responses": {
                    "200": { "description": "OK", "schema": { "$ref": "#/definitions/APIResponse" } },
                    "403": { "description": "Forbidden", "schema": { "$ref": "#/definitions/APIResponse" } }
                }
            }
        },
        "/admin/applications": {
            "get": {
                "security": [{ "BearerAuth": [] }],
                "description": "Admin retrieves all applications",
                "produces": ["application/json"],
                "tags": ["Admin"],
                "summary": "[Admin] List all applications",
                "parameters": [
                    { "type": "integer", "default": 1, "name": "page", "in": "query" },
                    { "type": "integer", "default": 10, "name": "page_size", "in": "query" }
                ],
                "responses": {
                    "200": { "description": "OK", "schema": { "$ref": "#/definitions/APIResponse" } },
                    "403": { "description": "Forbidden", "schema": { "$ref": "#/definitions/APIResponse" } }
                }
            }
        }
    },
    "definitions": {
        "APIResponse": {
            "type": "object",
            "properties": {
                "success": { "type": "boolean" },
                "message": { "type": "string" },
                "data": {},
                "error": {}
            }
        },
        "RegisterInput": {
            "type": "object",
            "required": ["name", "email", "password", "role"],
            "properties": {
                "name":     { "type": "string", "example": "Alice Smith" },
                "email":    { "type": "string", "example": "alice@example.com" },
                "password": { "type": "string", "example": "secret123" },
                "role":     { "type": "string", "enum": ["ADMIN", "RECRUITER", "CANDIDATE"], "example": "CANDIDATE" }
            }
        },
        "LoginInput": {
            "type": "object",
            "required": ["email", "password"],
            "properties": {
                "email":    { "type": "string", "example": "alice@example.com" },
                "password": { "type": "string", "example": "secret123" }
            }
        },
        "CreateJobInput": {
            "type": "object",
            "required": ["title", "description", "company", "location"],
            "properties": {
                "title":       { "type": "string", "example": "Senior Go Engineer" },
                "description": { "type": "string", "example": "We are looking for an experienced Go developer." },
                "company":     { "type": "string", "example": "Acme Corp" },
                "location":    { "type": "string", "example": "New York, NY" }
            }
        },
        "UpdateJobInput": {
            "type": "object",
            "properties": {
                "title":       { "type": "string", "example": "Lead Go Engineer" },
                "description": { "type": "string", "example": "Updated description." },
                "company":     { "type": "string", "example": "Acme Corp" },
                "location":    { "type": "string", "example": "Remote" }
            }
        },
        "UpdateStatusInput": {
            "type": "object",
            "required": ["status"],
            "properties": {
                "status": { "type": "string", "enum": ["APPLIED", "REVIEWED", "REJECTED", "ACCEPTED"], "example": "ACCEPTED" }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header",
            "description": "Enter your JWT token as: Bearer \u003ctoken\u003e"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Job Portal API",
	Description:      "A production-ready Job Portal backend with role-based access control.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
